services:
  - type: web
    name: gpt4o-chat-app
    env: node
    plan: free
    buildCommand: 'npm install'
    startCommand: 'node server/server.js'
    autoDeploy: true
    disk:
      name: persistent-disk
      mountPath: /uploads
      sizeGB: 1
